[2023-01-05 00:00:11,700] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.delete_cluster_dataproc_task manual__2023-01-04T23:38:06.495566+00:00 [queued]>
[2023-01-05 00:00:11,709] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.delete_cluster_dataproc_task manual__2023-01-04T23:38:06.495566+00:00 [queued]>
[2023-01-05 00:00:11,709] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 00:00:11,709] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-05 00:00:11,709] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 00:00:11,722] {taskinstance.py:1377} INFO - Executing <Task(DataprocDeleteClusterOperator): delete_cluster_dataproc_task> on 2023-01-04 23:38:06.495566+00:00
[2023-01-05 00:00:11,730] {standard_task_runner.py:52} INFO - Started process 1107 to run task
[2023-01-05 00:00:11,737] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'delete_cluster_dataproc_task', 'manual__2023-01-04T23:38:06.495566+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmprmith1x1', '--error-file', '/tmp/tmps00_lsdo']
[2023-01-05 00:00:11,738] {standard_task_runner.py:80} INFO - Job 35: Subtask delete_cluster_dataproc_task
[2023-01-05 00:00:11,799] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.delete_cluster_dataproc_task manual__2023-01-04T23:38:06.495566+00:00 [running]> on host 2302f2c95f83
[2023-01-05 00:00:11,868] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=delete_cluster_dataproc_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T23:38:06.495566+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T23:38:06.495566+00:00
[2023-01-05 00:00:11,871] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-05 00:00:11,871] {dataproc.py:816} INFO - Deleting cluster: move-data
[2023-01-05 00:00:46,713] {dataproc.py:828} INFO - Cluster deleted.
[2023-01-05 00:00:46,728] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=stock_data_pipeline_dag, task_id=delete_cluster_dataproc_task, execution_date=20230104T233806, start_date=20230105T000011, end_date=20230105T000046
[2023-01-05 00:00:46,782] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-05 00:00:46,807] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
