[2023-01-04 21:04:57,131] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.download_stock_data_from_datalake_task manual__2023-01-04T21:04:55.756534+00:00 [queued]>
[2023-01-04 21:04:57,140] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.download_stock_data_from_datalake_task manual__2023-01-04T21:04:55.756534+00:00 [queued]>
[2023-01-04 21:04:57,140] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 21:04:57,140] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-01-04 21:04:57,140] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 21:04:57,151] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): download_stock_data_from_datalake_task> on 2023-01-04 21:04:55.756534+00:00
[2023-01-04 21:04:57,159] {standard_task_runner.py:52} INFO - Started process 914 to run task
[2023-01-04 21:04:57,163] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'download_stock_data_from_datalake_task', 'manual__2023-01-04T21:04:55.756534+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmps9faf9wd', '--error-file', '/tmp/tmprvuzzktx']
[2023-01-04 21:04:57,164] {standard_task_runner.py:80} INFO - Job 7: Subtask download_stock_data_from_datalake_task
[2023-01-04 21:04:57,220] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.download_stock_data_from_datalake_task manual__2023-01-04T21:04:55.756534+00:00 [running]> on host e35cd2348433
[2023-01-04 21:04:57,288] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=download_stock_data_from_datalake_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T21:04:55.756534+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T21:04:55.756534+00:00
[2023-01-04 21:04:57,290] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-04 21:04:57,291] {subprocess.py:74} INFO - Running command: ['bash', '-c', "python 'Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py'"]
[2023-01-04 21:04:57,324] {subprocess.py:85} INFO - Output:
[2023-01-04 21:04:57,395] {subprocess.py:92} INFO - python: can't open file '/tmp/***tmpefcyfz3y/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py': [Errno 2] No such file or directory
[2023-01-04 21:04:57,399] {subprocess.py:96} INFO - Command exited with return code 2
[2023-01-04 21:04:57,417] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-01-04 21:04:57,420] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_data_pipeline_dag, task_id=download_stock_data_from_datalake_task, execution_date=20230104T210455, start_date=20230104T210457, end_date=20230104T210457
[2023-01-04 21:04:57,432] {standard_task_runner.py:92} ERROR - Failed to execute job 7 for task download_stock_data_from_datalake_task (Bash command failed. The command returned a non-zero exit code 2.; 914)
[2023-01-04 21:04:57,456] {local_task_job.py:156} INFO - Task exited with return code 1
