[2023-01-07 00:56:12,085] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_SP_500_data_to_datalake_task manual__2023-01-07T00:56:10.803336+00:00 [queued]>
[2023-01-07 00:56:12,093] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_SP_500_data_to_datalake_task manual__2023-01-07T00:56:10.803336+00:00 [queued]>
[2023-01-07 00:56:12,093] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-07 00:56:12,093] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-07 00:56:12,093] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-07 00:56:12,105] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_SP_500_data_to_datalake_task> on 2023-01-07 00:56:10.803336+00:00
[2023-01-07 00:56:12,111] {standard_task_runner.py:52} INFO - Started process 8345 to run task
[2023-01-07 00:56:12,116] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'upload_SP_500_data_to_datalake_task', 'manual__2023-01-07T00:56:10.803336+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpazh87m4_', '--error-file', '/tmp/tmpda88glsg']
[2023-01-07 00:56:12,117] {standard_task_runner.py:80} INFO - Job 94: Subtask upload_SP_500_data_to_datalake_task
[2023-01-07 00:56:12,175] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.upload_SP_500_data_to_datalake_task manual__2023-01-07T00:56:10.803336+00:00 [running]> on host 60ad85e83037
[2023-01-07 00:56:12,240] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=upload_SP_500_data_to_datalake_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-07T00:56:10.803336+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-07T00:56:10.803336+00:00
[2023-01-07 00:56:15,117] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 67, in main
    beg_date, end_date = date_range(ticker)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 40, in date_range
    assert beg_date < end_date, "Beginning Date is in the Future"
TypeError: can't compare offset-naive and offset-aware datetimes
[2023-01-07 00:56:15,127] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=stock_data_pipeline_dag, task_id=upload_SP_500_data_to_datalake_task, execution_date=20230107T005610, start_date=20230107T005612, end_date=20230107T005615
[2023-01-07 00:56:15,137] {standard_task_runner.py:92} ERROR - Failed to execute job 94 for task upload_SP_500_data_to_datalake_task (can't compare offset-naive and offset-aware datetimes; 8345)
[2023-01-07 00:56:15,176] {local_task_job.py:156} INFO - Task exited with return code 1
