[2023-01-06 00:04:45,743] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_btc_data_to_datalake_task manual__2023-01-06T00:04:44.209851+00:00 [queued]>
[2023-01-06 00:04:45,752] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_btc_data_to_datalake_task manual__2023-01-06T00:04:44.209851+00:00 [queued]>
[2023-01-06 00:04:45,753] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 00:04:45,753] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-06 00:04:45,753] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 00:04:45,765] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_btc_data_to_datalake_task> on 2023-01-06 00:04:44.209851+00:00
[2023-01-06 00:04:45,772] {standard_task_runner.py:52} INFO - Started process 5684 to run task
[2023-01-06 00:04:45,777] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'upload_btc_data_to_datalake_task', 'manual__2023-01-06T00:04:44.209851+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp4a1d0fwq', '--error-file', '/tmp/tmpo5frbt7g']
[2023-01-06 00:04:45,778] {standard_task_runner.py:80} INFO - Job 71: Subtask upload_btc_data_to_datalake_task
[2023-01-06 00:04:45,843] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.upload_btc_data_to_datalake_task manual__2023-01-06T00:04:44.209851+00:00 [running]> on host 7aa3417b2d87
[2023-01-06 00:04:45,923] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=upload_btc_data_to_datalake_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:04:44.209851+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T00:04:44.209851+00:00
[2023-01-06 00:12:05,214] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 61, in main
    beg_date, end_date = date_range(ticker)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 33, in date_range
    beg_date = datetime.strptime(temp_date, "%Y-%m-%d")
UnboundLocalError: local variable 'temp_date' referenced before assignment
[2023-01-06 00:12:05,225] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=stock_data_pipeline_dag, task_id=upload_btc_data_to_datalake_task, execution_date=20230106T000444, start_date=20230106T000445, end_date=20230106T001205
[2023-01-06 00:12:05,238] {standard_task_runner.py:92} ERROR - Failed to execute job 71 for task upload_btc_data_to_datalake_task (local variable 'temp_date' referenced before assignment; 5684)
[2023-01-06 00:12:05,294] {local_task_job.py:156} INFO - Task exited with return code 1
