[2023-01-04 23:48:38,264] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task manual__2023-01-04T23:38:06.495566+00:00 [queued]>
[2023-01-04 23:48:38,273] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task manual__2023-01-04T23:38:06.495566+00:00 [queued]>
[2023-01-04 23:48:38,273] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 23:48:38,273] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 23:48:38,273] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 23:48:38,284] {taskinstance.py:1377} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster_dataproc_task> on 2023-01-04 23:38:06.495566+00:00
[2023-01-04 23:48:38,293] {standard_task_runner.py:52} INFO - Started process 459 to run task
[2023-01-04 23:48:38,297] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'create_cluster_dataproc_task', 'manual__2023-01-04T23:38:06.495566+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpfxcgq54e', '--error-file', '/tmp/tmp6ybbaq50']
[2023-01-04 23:48:38,298] {standard_task_runner.py:80} INFO - Job 33: Subtask create_cluster_dataproc_task
[2023-01-04 23:48:38,356] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.create_cluster_dataproc_task manual__2023-01-04T23:38:06.495566+00:00 [running]> on host 2302f2c95f83
[2023-01-04 23:48:38,427] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=create_cluster_dataproc_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T23:38:06.495566+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T23:38:06.495566+00:00
[2023-01-04 23:48:38,429] {dataproc.py:590} INFO - Creating cluster: move-data
[2023-01-04 23:48:38,430] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-04 23:51:28,920] {dataproc.py:534} INFO - Cluster created.
[2023-01-04 23:51:28,949] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=stock_data_pipeline_dag, task_id=create_cluster_dataproc_task, execution_date=20230104T233806, start_date=20230104T234838, end_date=20230104T235128
[2023-01-04 23:51:29,002] {local_task_job.py:156} INFO - Task exited with return code 0
