[2023-01-07 00:49:37,123] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_SP_500_data_to_datalake_task manual__2023-01-07T00:49:35.954707+00:00 [queued]>
[2023-01-07 00:49:37,132] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_SP_500_data_to_datalake_task manual__2023-01-07T00:49:35.954707+00:00 [queued]>
[2023-01-07 00:49:37,132] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-07 00:49:37,132] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-07 00:49:37,132] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-07 00:49:37,143] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_SP_500_data_to_datalake_task> on 2023-01-07 00:49:35.954707+00:00
[2023-01-07 00:49:37,150] {standard_task_runner.py:52} INFO - Started process 8086 to run task
[2023-01-07 00:49:37,154] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'upload_SP_500_data_to_datalake_task', 'manual__2023-01-07T00:49:35.954707+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpmxp8iaqc', '--error-file', '/tmp/tmpqdmvpn11']
[2023-01-07 00:49:37,156] {standard_task_runner.py:80} INFO - Job 90: Subtask upload_SP_500_data_to_datalake_task
[2023-01-07 00:49:37,212] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.upload_SP_500_data_to_datalake_task manual__2023-01-07T00:49:35.954707+00:00 [running]> on host 60ad85e83037
[2023-01-07 00:49:37,278] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=upload_SP_500_data_to_datalake_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-07T00:49:35.954707+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-07T00:49:35.954707+00:00
[2023-01-07 00:49:40,362] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 66, in main
    beg_date, end_date = date_range(ticker)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 37, in date_range
    tzinfo=ZoneInfo("America/Detroit")
NameError: name 'ZoneInfo' is not defined
[2023-01-07 00:49:40,373] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=stock_data_pipeline_dag, task_id=upload_SP_500_data_to_datalake_task, execution_date=20230107T004935, start_date=20230107T004937, end_date=20230107T004940
[2023-01-07 00:49:40,385] {standard_task_runner.py:92} ERROR - Failed to execute job 90 for task upload_SP_500_data_to_datalake_task (name 'ZoneInfo' is not defined; 8086)
[2023-01-07 00:49:40,419] {local_task_job.py:156} INFO - Task exited with return code 1
